### PR TITLE
Center toc heading

### LINKED ISSUE #8: ToC heading is not centered
image

### PR DESCRIPTION
**Pull request by joel-lim**
Fixes #8 
Fix table of contents heading to be center-aligned

### CODE REVIEW

**Comment by damithc** [comment]
@joel-lim thanks for the PR. Ready for review/merging?

**Comment by joel-lim** [comment]
Yup!

**Comment by damithc** [comment]
Added the `Fixes #8` to the PR description.

**Comment by damithc** [comment]
Seems to be fixed now. Thanks @joel-lim

**Pull request merged**
